variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "ros-indigo-common-msgs ros-indigo-tf2-ros ros-indigo-xacro ros-indigo-rviz-animated-view-controller libltdl-dev libgeos++-dev libgeos-dev libtinyxml2-dev libboost-all-dev libltdl-dev"
  GIT_DEPENDENCIES: "jbeder/yaml-cpp jrl-umi3218/SpaceVecAlg jrl-umi3218/RBDyn jrl-umi3218/eigen-qld jrl-umi3218/eigen-quadprog jrl-umi3218/sch-core jrl-umi3218/Tasks jrl-umi3218/mc_rbdyn_urdf nanomsg/nanomsg humanoid-path-planner/hpp-spline#v4.8.1"
  ROS_GIT_DEPENDENCIES: "jrl-umi3218/mc_rtc_data jrl-umi3218/mc_rtc_msgs"
  MASTER_PPA: ""
  ROS_DISTRO: "indigo"
  ALLOW_CATKINLINT_FAILURE: "true"
  CMAKE_ADDITIONAL_OPTIONS: "-DPYTHON_BINDING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_PYTHON_INTERFACE:BOOL=OFF -DYAML_BUILD_SHARED_LIBS:BOOL=ON"

clang-format:
  stage: clang-format
  before_script: []
  script:
    - ./.clang-format-check.sh
  tags:
    - clang-format

before_script:
  - git submodule update --quiet --init --recursive
  - add-apt-repository ppa:pierre-gergondet+ppa/multi-contact-unstable && apt-get update && apt-get upgrade cmake libeigen3-dev -qq
  - rm -rf debian
  - ./.jrl-ci/dependencies/catkin
  - ./.jrl-ci/run before_install

build_gcc:
  stage: build
  script:
    - export APT_DEPENDENCIES=""
    - export GIT_DEPENDENCIES="jrl-umi3218/mc_rtc"
    - export ROS_GIT_DEPENDENCIES=""
    - . /tmp/_ci/catkin_dep_ws/devel/setup.sh
    - ./.jrl-ci/run before_install
    - cd $HOME
    - wget https://sourceforge.net/projects/qwt/files/qwt/6.1.4/qwt-6.1.4.tar.bz2
    - tar xjf qwt-6.1.4.tar.bz2
    - cd qwt-6.1.4
    - sed -i -e's@QWT_INSTALL_PREFIX    = /usr/local/qwt-$$QWT_VERSION@QWT_INSTALL_PREFIX = /usr/local@' qwtconfig.pri
    - sed -i -e's@QWT_INSTALL_HEADERS   = $${QWT_INSTALL_PREFIX}/include@QWT_INSTALL_HEADERS = $${QWT_INSTALL_PREFIX}/include/qwt@' qwtconfig.pri
    - qmake && make && make install
    - cd $CI_PROJECT_DIR
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - clang-format
  - build
