variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "ros-indigo-common-msgs ros-indigo-tf2-ros ros-indigo-xacro ros-indigo-rviz-animated-view-controller libtasks-qld-dev libmc-rbdyn-urdf-dev libltdl-dev libgeos++-dev libgeos-dev"
  GIT_DEPENDENCIES: "nanomsg/nanomsg"
  ROS_GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/mc_rtc_ros_data"
  MASTER_PPA: "pierre-gergondet+ppa/multi-contact-unstable"
  ROS_DISTRO: "indigo"
  ALLOW_CATKINLINT_FAILURE: "true"
  CMAKE_ADDITIONAL_OPTIONS: "-DPYTHON_BINDING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo"

clang-format:
  stage: clang-format
  before_script: []
  script:
    - ./.clang-format-check.sh
  tags:
    - clang-format

before_script:
  - git submodule update --quiet --init --recursive
  - add-apt-repository ppa:pierre-gergondet+ppa/multi-contact-unstable && apt-get update && apt-get upgrade cmake libeigen3-dev -qq
  - ./.jrl-ci/dependencies/catkin
  - ./.jrl-ci/run before_install

build_gcc:
  stage: build
  script:
    - export APT_DEPENDENCIES=""
    - export GIT_DEPENDENCIES="git@gite.lirmm.fr:multi-contact/mc_rtc"
    - export ROS_GIT_DEPENDENCIES=""
    - . /tmp/_ci/catkin_dep_ws/devel/setup.sh
    - ./.jrl-ci/run before_install
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - clang-format
  - build
