variables:
  CI_TOOL: gitlab-ci
  APT_DEPENDENCIES: "libtinyxml2-dev libboost-all-dev libjsoncpp-dev libgeos++-dev libgeos-dev qhull-bin libqhull-dev libltdl-dev libspacevecalg-dev libeigen-qld-dev librbdyn-dev libsch-core-dev ros-indigo-common-msgs ros-indigo-tf2-ros ros-indigo-xacro ros-indigo-rviz-animated-view-controller libglfw3-dev"
  GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/eigen-lssol.git jrl-umi3218/Tasks git@gite.lirmm.fr:multi-contact/mc_rbdyn_urdf_cpp.git git@gite.lirmm.fr:multi-contact/mc_rtc"
  ROS_GIT_DEPENDENCIES: "git@gite.lirmm.fr:multi-contact/mc_ros#karim_drc git@gite.lirmm.fr:mc-hrp2/hrp2_drc#master git@gite.lirmm.fr:mc-hrp4/hrp4#master"
  MASTER_PPA: "v-launchpad-jochen-sprickerhof-de/pcl pierre-gergondet+ppa/multi-contact-unstable hrg/daily keithw/glfw3"
  ROS_DISTRO: "indigo"

before_script:
  - git submodule update --quiet --init --recursive
  - ./.jrl-ci/dependencies/eigen-3.2
  - ./.jrl-ci/dependencies/catkin
  - ./.jrl-ci/run before_install

build_gcc:
  stage: build
  script:
    - ./.jrl-ci/run build
    - ./.jrl-ci/run after_success
  tags:
    - GCC

stages:
  - build
